version: "3.8"
services:
  plc-exporter:
    build:
      context: ../../
      dockerfile: cmd/plc/Dockerfile
    restart: always
    image: plc-exporter
    container_name: plc-exporter
    environment:
      - PLC_EXPORTER_CHECK_INTERVAL=5s
      - PLC_EXPORTER_DATA_DIR=/data
    ports:
      - "3260:3260"
    volumes:
      - ../../data/plc-exporter:/data
