version: "3.8"
services:
  plc-exporter:
    build:
      context: ../../
      dockerfile: cmd/plc/Dockerfile
    restart: always
    image: plc-exporter
    container_name: plc-exporter
    environment:
      - PLC_MIRROR_CHECK_INTERVAL=5s
      - PLC_MIRROR_DATA_DIR=/data/plc-exporter
    ports:
      - "3260:3260"
    volumes:
      - ./data/plc-exporter:/data
