version: "3.8"
services:
  looking-glass-consumer:
    build:
      context: .
      dockerfile: cmd/stream/Dockerfile
    restart: always
    image: looking-glass-consumer
    container_name: looking-glass-consumer
    environment:
      - LG_WS_URL=wss://bsky.network/xrpc/com.atproto.sync.subscribeRepos
      - LG_PORT=8080
      - LG_DEBUG=false
      - LG_SQLITE_PATH=/data/looking-glass.db
      - LG_MIGRATE_DB=true
      - LG_EVT_RECORD_TTL=48h
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
    env_file:
      - .lg.env
    ports:
      - "6962:8080"
    volumes:
      - ./data/lg-consumer:/data
      - ~/.config/gcloud/application_default_credentials.json:/gcp/creds.json:ro
